# language: zh-CN
# Auto-generated by cucumber_test/tools/generate_xiaodu_formal_feature.py.
# 新增/删除/修改正式用例时，优先调整 Examples 或重新生成本文件；step 执行逻辑保持不变。
@formal @project:csk5062_xiaodu_fan @cucumber_formal
功能: 小度 5062 正式全链路 Cucumber 执行
  为了让正式全集可以由 Cucumber 用例驱动并输出统一结果
  作为 Trisolaris 验证执行器
  我需要先执行小度正式全链路，再按正式用例表逐条校验状态

  背景:
    假如 当前小度正式 Cucumber 环境已准备

  @case_id:XIAODU-CUKE-FULLFLOW-EXEC @execution
  场景: XIAODU-CUKE-FULLFLOW-EXEC 执行小度正式全链路全集
    当 通过 Cucumber 执行小度正式全集
    那么 正式聚合结果应包含 72 条用例

  @formal_case_status
  场景大纲: <case_id> 正式用例状态应符合需求期望
    假如 小度 Cucumber 正式全集结果已存在
    那么 正式用例 "<case_id>" 的实际状态应为 "<expected_status>"

    例子:
      | case_id | expected_status |
      | ENV-001 | PASS |
      | ENV-002 | PASS |
      | SESS-001 | TODO |
      | SESS-002 | PASS |
      | SESS-003 | PASS |
      | SESS-004 | PASS |
      | SESS-005 | PASS |
      | SESS-006 | PASS |
      | SESS-007 | PASS |
      | CTRL-001 | PASS |
      | CTRL-002 | PASS |
      | CTRL-003 | PASS |
      | CTRL-004 | PASS |
      | VOL-001 | PASS |
      | VOL-002 | PASS |
      | VOL-003 | PASS |
      | VOL-004 | PASS |
      | REPORT-001 | PASS |
      | REPORT-002 | PASS |
      | REPORT-003 | PASS |
      | REPORT-004 | PASS |
      | VOICE-001 | PASS |
      | VOICE-002 | PASS |
      | VOICE-003 | PASS |
      | VOICE-004 | PASS |
      | VOICE-005 | PASS |
      | SWAKE-001 | PASS |
      | SWAKE-002 | PASS |
      | SWAKE-003 | PASS |
      | SWAKE-004 | PASS |
      | SWAKE-005 | PASS |
      | SWAKE-006 | PASS |
      | SWAKE-007 | PASS |
      | REG-ENTRY-001 | PASS |
      | REG-ENTRY-002 | PASS |
      | REG-ENTRY-003 | PASS |
      | REG-EXIT-001 | PASS |
      | REG-CMD-001 | PASS |
      | REG-CMD-002 | PASS |
      | REG-CMD-003 | PASS |
      | REG-WAKE-001 | PASS |
      | REG-WAKE-002 | PASS |
      | REG-WAKE-003 | PASS |
      | REG-WAKE-004 | PASS |
      | REG-FLOW-001 | PASS |
      | REG-SAVE-001 | PASS |
      | REG-SAVE-002 | PASS |
      | REG-FAIL-001 | PASS |
      | REG-FAIL-002 | PASS |
      | REG-FAIL-003 | PASS |
      | REG-FAIL-004 | PASS |
      | REG-CONFLICT-001 | PASS |
      | REG-CONFLICT-002 | PASS |
      | REG-CONFLICT-003 | PASS |
      | REG-CONFLICT-004 | PASS |
      | REG-DEL-001 | PASS |
      | REG-DEL-002 | PASS |
      | REG-DEL-003 | PASS |
      | REG-DEL-004 | PASS |
      | CFG-AUDIO-001 | PASS |
      | CFG-WAKE-001 | PASS |
      | CFG-VOL-001 | PASS |
      | CFG-VOL-002 | PASS |
      | CFG-PROTO-001 | PASS |
      | CFG-PROTO-002 | PASS |
      | CFG-PROTO-003 | PASS |
      | REG-CFG-001 | PASS |
      | REG-CFG-002 | PASS |
      | REG-CFG-003 | PASS |
      | REG-CFG-004 | PASS |
      | REG-CFG-005 | PASS |
      | REG-CFG-006 | PASS |
