#ifndef __IVW_RES_TYPE_H__
#define __IVW_RES_TYPE_H__

#include "ivw_type.h"

typedef enum
{
	FSMN = 0,
	WFSA,
	KEYWORD_MAIN,
	KEYWORD_ASR,
	MLP_CNN,
	MLP_CNN_SHUFFLENETV2,
	MLP_CNN_RESGROUP,
	MLP_CNN_RESGROUP_E2E,
	MLP_CNN_RESGROUP_FREE,
	MLP_GROUP_CNN_V2,
	MLP_CNN_SHUFFLENETV2_IVW,
	KEYWORD_CUSTOM,
	MLP_CNN_UNET,
	MLP_CNN_RESGROUP_MULTIMIC,
	MLP_CNN_RESGROUP_4BIT,
	MLP_CNN_E2E_GATE,
	MLP_CNN_RESGROUP_SYLLABLE,
	MLP_CNN_RESGROUP_MULTIMIC_4BIT,
	MLP_CNN_RESGROUP_MC_SYLLABLE,
	MLP_CONFIDENCE,
	MLP_CNN_RESGROUP_MC_E2E_NEW,
	MLP_CNN_RESGROUP_E2E_NEW,
	MLP_CNN_RESGROUP_FREE_NEW,
	MLP_DFSMN,
	MLP_CNN_RESGROUP_E2E_SYL_4BIT,
	MLP_CNN_RESGROUP_E2E_MONO_4BIT,
	MLP_CNN_RESGROUP_TEXT_MATCH,
	KEYWORD_VOICE,
	IVW_RES_COUNT		//new ResType is added before IVW_RES_COUNT
}EIvwResType;

#endif
