#pragma once

#define WAKEUP_END_STATE_DEFAULT_JUDGEMENT_TOPN		(5)
#define WAKEUP_END_STATE_DEFAULT_CONTINUE_FRAME		(2)
#define WAKEUP_END_STATE_DEFAULT_MAX_DELAY_FRAME	(8)


typedef enum
{
	PARAM_NONE = 0,

	//IVW
	PARAM_W_IVW = 1100,
	PARAM_W_IVW_VADON,	//0-VAD OFF; 1-VAD ON
	PARAM_W_IVW_VAD_MAX_FRAME_FLUSH_STRATEGY,
	PARAM_W_IVW_VAD_FLUSH_MAX_FRAME,
	PARAM_W_IVW_VADTYPE, // 0-energy vad; 1-model vad
	PARAM_W_IVW_FSP_ENABLE,	//0: only command; 1: only freecommand; 2: both has command and freecommand
	PARAM_W_IVW_HISTORY_RESET_FLAG, //[0]:mlp history reset flag, [1]:e2e history reset flag, 1-reset 0-no reset per flag
	PARAM_W_IVW_E2E_ENABLE,	//0-E2E OFF; 1-E2E ON
	PARAM_W_IVW_SYLLABLE_ENABLE,//0-SYLLABLE OFF; 1-SYLLABLE ON,default ON
	PARAM_W_IVW_NO_INNER_PK,
	PARAM_W_IVW_DUMP_FEA,
	PARAM_W_IVW_DUMP_MLP_POSTERIOR,
	PARAM_W_IVW_DUMP_MLP_MASK_DEC,
	PARAM_W_IVW_ASR_FAST_WAKEUP,//0-ASR FAST WAKEUP OFF; ASR FAST WAKEUP-VAD ON,default ON
	PARAM_W_IVW_MAIN_WAKE_USE_E2E,
	PARAM_W_IVW_MAIN_WAKE_E2E_THRESHOLD,			//e2e main threshold,ln(probability)
	PARAM_W_IVW_MAIN_WAKE_E2E_NEED_NODE_NUMS_DISCARD,
	PARAM_W_IVW_MAIN_WAKE_E2E_NEED_DELAY_NUMS,	//e2e_new delay frame
	PARAM_W_IVW_MAIN_WAKE_ONLY_E2E_INTERVAL_NUMS,	//e2e_new interval frame when only e2e branch
	PARAM_W_IVW_MAIN_WAKE_ONLY_E2E_DURATION_NUMS,	//e2e_new duration frame(fake) when only e2e branch
	PARAM_W_IVW_WAKEUP_END_STATE_DELAY_ENABLE,	//0-WakeupEndStateDelay OFF; 1-WakeupEndStateDelay ON,default OFF
	PARAM_W_IVW_WAKEUP_END_STATE_JUDGEMENT_TOPN,
	PARAM_W_IVW_WAKEUP_END_STATE_CONTINUE_FRAME,
	PARAM_W_IVW_WAKEUP_END_STATE_MAX_DELAY_FRAME,
	PARAM_W_IVW_MAIN_WAKE_E2E_LOW_THRESHOLD,				//e2e main low threshold,ln(probability)
	PARAM_W_IVW_MAIN_WAKE_E2E_MIN_LOW_WAKE_FRAME,		//e2e main min low threshold wake frame
	PARAM_W_IVW_MAIN_WAKE_E2E_MAX_LOW_WAKE_FRAME,		//e2e main maxs low threshold wake frame
	PARAM_W_IVW_FSP_VAD_INTERVAL,
	PARAM_W_IVW_FSP_ENDPOINT_INTERVAL_NUMS,
	PARAM_W_IVW_FSP_WAKE_E2E_DURATION_NUMS,
	PARAM_W_IVW_FSP_PK_WIN_FRMAES,
	PARAM_W_IVW_MLC_WAKE_ONLY_E2E_INTERVAL_NUMS,
	PARAM_W_IVW_FSP_DUL_INTENT_START_ID,
	PARAM_W_IVW_FSP_CHECK_VAD_FLAG,
	PARAM_W_IVW_MLC_DUL_INTENT_ON,
	PARAM_W_IVW_SHARED_MEM_RELEASE,
	PARAM_W_IVW_PK_WITHOUT_VAD,
	PARAM_W_IVW_DUL_INTENT_RANGE,
	PARAM_W_IVW_DUL_INTENT_DISTANCE,
	PARAM_W_IVW_VAD_END_AGAIN_FRAMES,

	PARAM_W_IVW_VOICE_REGIST_HIGH_SENSITIVITY_MAIN_THRESHOLD = 1160,
	PARAM_W_IVW_VOICE_REGIST_HIGH_SENSITIVITY_ASR_THRESHOLD,
	PARAM_W_IVW_VOICE_REGIST_MID_SENSITIVITY_MAIN_THRESHOLD,
	PARAM_W_IVW_VOICE_REGIST_MID_SENSITIVITY_ASR_THRESHOLD,
	PARAM_W_IVW_VOICE_REGIST_LOW_SENSITIVITY_MAIN_THRESHOLD,
	PARAM_W_IVW_VOICE_REGIST_LOW_SENSITIVITY_ASR_THRESHOLD,

	PARAM_W_IVW_VOICE_REGIST_MODE = 1170,
	PARAM_W_IVW_VOICE_REGIST_SPEED_CHECK_ON,
	PARAM_W_IVW_VOICE_REGIST_MIN_SAMPLE_VALUE,
	PARAM_W_IVW_VOICE_REGIST_CONFLICT_CHECK_ON,
	PARAM_W_IVW_VOICE_REGIST_SIMILARITY_THRESHOLD,
	PARAM_W_IVW_VOICE_REGIST_PCM_MIN_FRAME,
	PARAM_W_IVW_VOICE_REGIST_FORWARD_FRAME_NUMS,
	PARAM_W_IVW_VOICE_REGIST_BACK_FRAME_NUMS,
	
	PARAM_W_IVW_MAIN_WAKE_E2E_NEED_NODE_NUMS = 1180,
	PARAM_W_IVW_MAIN_WAKE_E2E_NEED_NODE_WIN,
	PARAM_W_IVW_MLC_WAKE_E2E_NEED_NODE_NUMS,
	PARAM_W_IVW_MLC_WAKE_E2E_NEED_NODE_WIN,
	PARAM_W_IVW_FSP_WAKE_E2E_NEED_NODE_NUMS,
	PARAM_W_IVW_FSP_WAKE_E2E_NEED_NODE_WIN,

	//VAD
	PARAM_W_VAD							= 1200,
	PARAM_W_VAD_SAMPLERATE,
	PARAM_W_VAD_NENERGYTHRESHOLD,
	PARAM_W_VAD_NENDGAP,
	PARAM_W_VAD_ISDEBUGON,
	PARAM_W_VAD_ISLOGVADFILEOUT,
	PARAM_W_VAD_ISLOGVADFILEIN,

	//FEA
	PARAM_W_FEA							= 1300,
	PARAM_W_FEA_DO_CMN,	//0-NO CMN; 1-DO CMN
	PARAM_W_FEA_MLP_JUMPFREAM_NUM,
	PARAM_W_FEA_USE_MVA, // 0-NO MVA FEA, 1 DP MVA FEA
	PARAM_W_FEA_DENOISE_MASK_FLOOR, // 噪声mask floor
	PARAM_W_FEA_TYPE, // Inner Parm 0-NO PCEN, 1-PCEN
	PARAM_W_FEA_DIM, // Inner Parm 0-FB40, 1-FB80

	//MLP
	PARAM_W_MLP							= 1400,
	PARAM_W_MLP_E2E_SCORE_BUFFER_SIZE,		//0-15
	PARAM_W_MLP_DUMP_DIR,
	PARAM_W_MLP_SID,
	PARAM_W_MLP_B_DUMP_SYLLABLE_POSTERIOR,
	PARAM_W_MLP_REF_ZERO,
	PARAM_W_MLP_MLC_E2E_TOPN,
	PARAM_W_MLP_VAD_SIL_THRESHOLD,
	PARAM_W_MLP_VAD_START_CONTINUE_NUMS,
	PARAM_W_MLP_VAD_END_CONTINUE_NUMS,
	PARAM_W_MLP_E2E_MLC_NOISE_COEFFICIENT,
	PARAM_W_MLP_FREE_NOISE_COEFFICIENT,
	PARAM_W_MLP_VAD_LINK_COUNT,
	PARAM_W_MLP_VAD_LINK_FRAME_NUMS,
	PARAM_W_MLP_E2E_MAIN_NOISE_COEFFICIENT,

	//DEC
	PARAM_W_DEC							= 1500,
	//PREWAKE reserved
	PARAM_W_DEC_NCMTHRESHOLD_PREWAKE_KEYWORD1_ARC1 = 1501,

	//支持所有门限修改，PARAM = [PARAM_W_DEC_NCMTHRESHOLD_KEYWORD1_ARC1， PARAM_W_DEC_NCMTHRESHOLD_KEYWORD1_ARC1 + WDEC_PARAM_MAX_KEYWORD_NUM）
	PARAM_W_DEC_NCMTHRESHOLD_KEYWORD1_ARC1 = 1800,
	
	PARAM_W_DEC_NCMTHRESHOLD_END = 2099,

	PARAM_W_DEC_NLMPENALTY			    = 2100,
	PARAM_W_DEC_WARMUP,	//0-NO WARMUP 1-DO WARMUP

	PARAM_W_DEC_WAKEUP_MODE,

	PARAM_W_DEC_KEYWORD_TYPE,
	PARAM_W_DEC_KEYWORD_PREWAKEUP_PRESTATE,
	PARAM_W_DEC_WAKEUP_DELAY_FRAME_MAX,
	PARAM_W_DEC_WAKEUP_DELAY_FRAME_MIN,

	PARAM_W_DEC_ANAlYSIS,
	PARAM_W_DEC_WAKEUP_TOPN,
	PARAM_W_DEC_WAKEUP_TOPN_LEN,
	PARAM_W_DEC_B_DUMP_WAKE_UP_MLP_POSTERIOR,
	PARAM_W_DEC_N_LOG_CM,
	PARAM_W_DEC_N_LOG_CONTINUE_RESET_FRANE,
	PARAM_W_DEC_DUMP_DIR,
	PARAM_W_DEC_ASR_CONFIDENCE_ENABLE,
	PARAM_W_DEC_LOW_WAKEUP_CONFIDENCE_ENABLE,
	PARAM_W_DEC_MIN_LOW_WAKEUP_FRAME,
	PARAM_W_DEC_MAX_LOW_WAKEUP_FRAME,
	PARAM_W_DEC_WAKEUP_START_STATE_THRESHOLD,
	PARAM_W_DEC_THRESHOLD_GRADE,

	PARAM_W_DEC_MAIN_WAKE_E2E_THRESHOLD_ARC1 = 2121,			//e2e main threshold,ln(probability)
	PARAM_W_DEC_MAIN_WAKE_E2E_THRESHOLD_END = 2171,
	//PARAM_W_DEC_MLC_WAKE_E2E_THRESHOLD_ARC1 = 2131,			//e2e mlc threshold,ln(probability)
	//PARAM_W_DEC_MLC_WAKE_E2E_THRESHOLD_END = 2139,

	//PARAM_W_DEC_CONFIDENCE = 2150,
	//PARAM_W_DEC_CONFIDENCE_NCMTHRESHOLD = PARAM_W_DEC_CONFIDENCE,
	//PARAM_W_DEC_CONFIDENCE_NCMTHRESHOLD_END = PARAM_W_DEC_CONFIDENCE_NCMTHRESHOLD + 21,

	PARAM_W_DEC_WAKEUP_RESET = 2172,

	//RES 暂时只支持MLP_CNN、KEYWORD_MAIN、KEYWORD_ASR
	PARAM_W_RES = 2200,
	PARAM_W_RES_FSMN_PLATFORM,
	PARAM_W_RES_KEYWORD_MAIN_PLATFORM,
	PARAM_W_RES_KEYWORD_ASR_PLATFORM,
	PARAM_W_RES_MLP_CNN_PLATFORM,
	PARAM_W_RES_WFST_ASR_PLATFORM,

	//PLATFORM 0:ARM 1:CASTOR

	PARAM_W_RES_FSMN_RES_TYPES,
	PARAM_W_RES_MLP_CNN_RES_TYPES,
	PARAM_W_RES_WFST_ASR_RES_TYPES,
	PARAM_W_RES_KEYWORD_MAIN_RES_TYPES,
	PARAM_W_RES_KEYWORD_ASR_RES_TYPES,
	//RES_TYPES 0:FSMN 1:KEYWORD_MAIN 2:KEYWORD_ASR 3:MLP_CNN

	PARAM_W_RES_FSMN_VERSION,
	PARAM_W_RES_KEYWORD_MAIN_VERSION,
	PARAM_W_RES_KEYWORD_ASR_VERSION,
	PARAM_W_RES_MLP_CNN_VERSION,
	PARAM_W_RES_WFST_ASR_VERSION,

	//VERSION xxxx YY:主版本4个字符，次版本2个字符

	PARAM_W_RES_FSMN_CRC_CORRECT,
	PARAM_W_RES_KEYWORD_MAIN_CRC_CORRECT,
	PARAM_W_RES_KEYWORD_ASR_CRC_CORRECT,
	PARAM_W_RES_MLP_CNN_CRC_CORRECT,
	PARAM_W_RES_WFST_ASR_CRC_CORRECT,

	//CRC_CORRECT 0:crc校验错误 1：crc校验正确
	//MAX PARAM IND
	PARAM_W_MAX							= 2500
}PARAM;

