#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CASE_MD = ROOT / "deliverables" / "csk5062_xiaodu_fan" / "archive" / "测试用例-正式版.md"
DEFAULT_EXPECTED = ROOT / "cucumber_test" / "runtime" / "expected_status" / "xiaodu5062_formal_expected.json"
DEFAULT_OUT = ROOT / "cucumber_test" / "runtime" / "features" / "xiaodu_formal_fullflow.feature"


def extract_case_ids(case_md: Path) -> list[str]:
    ids: list[str] = []
    for line in case_md.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\|\s*`([A-Z0-9-]+)`\s*\|", line)
        if match:
            case_id = match.group(1)
            if case_id not in ids:
                ids.append(case_id)
    if not ids:
        raise RuntimeError(f"no case IDs found in {case_md}")
    return ids


def render(case_ids: list[str], expected_overrides: dict[str, str]) -> str:
    lines = [
        "# language: zh-CN",
        "# Auto-generated by cucumber_test/tools/generate_xiaodu_formal_feature.py.",
        "# 新增/删除/修改正式用例时，优先调整 Examples 或重新生成本文件；step 执行逻辑保持不变。",
        "@formal @project:csk5062_xiaodu_fan @cucumber_formal",
        "功能: 小度 5062 正式全链路 Cucumber 执行",
        "  为了让正式全集可以由 Cucumber 用例驱动并输出统一结果",
        "  作为 Trisolaris 验证执行器",
        "  我需要先执行小度正式全链路，再按正式用例表逐条校验状态",
        "",
        "  背景:",
        "    假如 当前小度正式 Cucumber 环境已准备",
        "",
        "  @case_id:XIAODU-CUKE-FULLFLOW-EXEC @execution",
        "  场景: XIAODU-CUKE-FULLFLOW-EXEC 执行小度正式全链路全集",
        "    当 通过 Cucumber 执行小度正式全集",
        "    那么 正式聚合结果应包含 72 条用例",
        "",
        "  @formal_case_status",
        "  场景大纲: <case_id> 正式用例状态应符合需求期望",
        "    假如 小度 Cucumber 正式全集结果已存在",
        "    那么 正式用例 \"<case_id>\" 的实际状态应为 \"<expected_status>\"",
        "",
        "    例子:",
        "      | case_id | expected_status |",
    ]
    for case_id in case_ids:
        expected = expected_overrides.get(case_id, "PASS")
        lines.append(f"      | {case_id} | {expected} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Xiaodu formal Cucumber feature from the formal case markdown.")
    parser.add_argument("--case-md", type=Path, default=DEFAULT_CASE_MD)
    parser.add_argument("--expected-overrides", type=Path, default=DEFAULT_EXPECTED)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    case_ids = extract_case_ids(args.case_md)
    overrides = json.loads(args.expected_overrides.read_text(encoding="utf-8")) if args.expected_overrides.exists() else {}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(case_ids, overrides), encoding="utf-8")
    print(args.out)
    print(f"cases={len(case_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
